import { Router } from "express";
import controller from "../controller/cuotas.controller.js";
const router = Router();
    router.get('/create-table-cuotas', controller.createTableCuotas);
    router.post('/cuotas', controller.addCuota);
    router.get('/to-see-mail-options', controller.toMakeArrayMailOptions);
    router.get('/to-make-links-mayo', controller.toMakeArrayMailOptionsMayo);
    router.get('/to-make-links-junio', controller.toMakeArrayMailOptionsJunio);
    router.get('/to-see-cuotas', controller.getAllCuotasByAllAlumnos);
    router.get('/cuotas', controller.getAllCuotas);
    router.get('/cuotas/abril', controller.getAllCuotasAbril);
    router.get('/cuotas/marzo', controller.getAllCuotasMarzo);
    router.get('/cuotas/mayo', controller.getAllCuotasMayo);
    router.get('/cuotas/junio', controller.getAllCuotasJunio);
    router.get('/cuotas/julio', controller.getAllCuotasJulio);
    router.get('/to-see-mailOptions', controller.toMakeArrayMailOptionsByModel);
    router.get('/cuotas/app', controller.App);
    router.get('/cuotas/month', controller.getAllCuotasByMonth);
    router.get('/alumnos-not-payed', controller.toGetAlumnosNotPayed);
    router.put('/cuotas/update/:idCuota', controller.updateStatusById );
    router.get('/cuotas/sum/:month', controller.getSumByMonth);
    router.get('/cuotas/sum', controller.getSumToday);
    router.get('/cuotas/suma/week', controller.getSumByLastWeek);
    router.get('/cuotas/suma/week-and-users', controller.getSumByLastWeekByUser);
    //New Part
    router.get('/cuotas/meses/:idAlumno', controller.getAllCuotasPayedByIdAlumno);
    router.get('/cuota/:idAlumno/:month', controller.toMakeOneLink);
export default router;